package org.bahmni.module.fhir2AddlExtension.api.translator.impl;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.nullValue;

import java.lang.reflect.Method;
import java.util.Collections;

import org.hl7.fhir.r4.model.Task;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.openmrs.module.fhir2.api.translators.ConceptTranslator;
import org.openmrs.module.fhir2.api.translators.ReferenceTranslator;
import org.openmrs.module.fhir2.api.translators.TaskInputTranslator;
import org.openmrs.module.fhir2.api.translators.TaskOutputTranslator;
import org.openmrs.module.fhir2.model.FhirTask;

@SuppressWarnings("unused")
@RunWith(MockitoJUnitRunner.class)
public class BahmniTaskTranslatorImplTest {
	
	@Mock
	private ReferenceTranslator referenceTranslator;
	
	@Mock
	private TaskInputTranslator taskInputTranslator;
	
	@Mock
	private TaskOutputTranslator taskOutputTranslator;
	
	@Mock
	private ConceptTranslator conceptTranslator;
	
	private BahmniTaskTranslatorImpl translator;
	
	@Before
	public void setup() throws Exception {
		translator = new BahmniTaskTranslatorImpl();
		setField("referenceTranslator", referenceTranslator);
		setField("taskInputTranslator", taskInputTranslator);
		setField("taskOutputTranslator", taskOutputTranslator);
		setField("conceptTranslator", conceptTranslator);
	}
	
	private void setField(String name, Object value) throws Exception {
		Class<?> clazz = translator.getClass().getSuperclass();
		Method setter = clazz.getDeclaredMethod("set" + Character.toUpperCase(name.charAt(0)) + name.substring(1), value
		        .getClass().getInterfaces()[0]);
		setter.setAccessible(true);
		setter.invoke(translator, value);
	}
	
	// ── toOpenmrsType (create) ───────────────────────────────────────────────
	
	@Test
	public void toOpenmrsType_shouldStoreDescriptionInNameField() {
		Task task = new Task();
		task.setDescription("PatientHistory");
		task.setStatus(Task.TaskStatus.COMPLETED);
		task.setIntent(Task.TaskIntent.ORDER);
		
		FhirTask result = translator.toOpenmrsType(task);
		
		assertThat(result.getName(), equalTo("PatientHistory"));
	}
	
	@Test
	public void toOpenmrsType_shouldNotOverwriteNameWhenDescriptionAbsent() {
		Task task = new Task();
		task.setStatus(Task.TaskStatus.COMPLETED);
		task.setIntent(Task.TaskIntent.ORDER);
		
		FhirTask result = translator.toOpenmrsType(task);
		
		// name is auto-generated as "Task/{uuid}" by super — just confirm description not applied
		assertThat(result.getDescription(), nullValue());
	}
	
	// ── toOpenmrsType (update) ───────────────────────────────────────────────
	
	@Test
	public void toOpenmrsTypeUpdate_shouldStoreDescriptionInNameField() {
		FhirTask existingTask = new FhirTask();
		existingTask.setInput(Collections.emptySet());
		existingTask.setOutput(Collections.emptySet());
		
		Task task = new Task();
		task.setDescription("ExaminationForm");
		task.setStatus(Task.TaskStatus.COMPLETED);
		task.setIntent(Task.TaskIntent.ORDER);
		
		FhirTask result = translator.toOpenmrsType(existingTask, task);
		
		assertThat(result.getName(), equalTo("ExaminationForm"));
	}
	
	// ── toFhirResource ───────────────────────────────────────────────────────
	
	@Test
	public void toFhirResource_shouldMapFormNameFromNameFieldToDescription() {
		FhirTask fhirTask = new FhirTask();
		fhirTask.setName("PatientHistory"); // plain name — no "/"
		fhirTask.setStatus(FhirTask.TaskStatus.COMPLETED);
		fhirTask.setIntent(FhirTask.TaskIntent.ORDER);
		fhirTask.setInput(Collections.emptySet());
		fhirTask.setOutput(Collections.emptySet());
		
		Task result = translator.toFhirResource(fhirTask);
		
		assertThat(result.getDescription(), equalTo("PatientHistory"));
	}
	
	@Test
	public void toFhirResource_shouldNotExposeAutoGeneratedNameAsDescription() {
		FhirTask fhirTask = new FhirTask();
		fhirTask.setName("Task/some-uuid-123"); // auto-generated pattern
		fhirTask.setStatus(FhirTask.TaskStatus.COMPLETED);
		fhirTask.setIntent(FhirTask.TaskIntent.ORDER);
		fhirTask.setInput(Collections.emptySet());
		fhirTask.setOutput(Collections.emptySet());
		
		Task result = translator.toFhirResource(fhirTask);
		
		assertThat(result.getDescription(), nullValue());
	}
	
	@Test
	public void toFhirResource_shouldNotSetDescriptionWhenNameIsNull() {
		FhirTask fhirTask = new FhirTask();
		fhirTask.setStatus(FhirTask.TaskStatus.COMPLETED);
		fhirTask.setIntent(FhirTask.TaskIntent.ORDER);
		fhirTask.setInput(Collections.emptySet());
		fhirTask.setOutput(Collections.emptySet());
		
		Task result = translator.toFhirResource(fhirTask);
		
		assertThat(result.getDescription(), nullValue());
	}
}
